#!/bin/bash
# The PlayBox Project
# Copyright (C)2018-2026 2Play! (S.R.)
# 03.2026

# If EmulationStation is running, kill it first to release framebuffer
if pgrep -x "emulationstatio" > /dev/null; then
    pkill -x "emulationstatio"
    sleep 1
fi

exec /home/pi/code/skysource/Skyscraper
